[fix] 채소의 일기 조회 시 조회 데이터 추가 (likeCount,commentCount, myLike )
Mojacknong/Farmus-Spring pull request #54
Opened 2024-07-31 03:43 UTC by Ryeolee

## #️⃣연관된 이슈

> ex) #52

## 📝작업 내용

> 채소의 모든 일기 조회 시 데이터 추가 / likeCount,commentCount, myLike

### 스크린샷 (선택)

> 없음

## 💬리뷰 요구사항(선택)

> 없음

2024-07-31 05:15 UTC, MinchoGreenT commented on src/main/java/com/modernfarmer/farmusspring/domain/myveggiegarden/dto/DiaryAll.java
DTO 클래스는 웬만하면 DTO라고 명시하는 것이 좋을 것 같습니다!

2024-07-31 05:16 UTC, MinchoGreenT commented on src/main/java/com/modernfarmer/farmusspring/domain/myveggiegarden/controller/MyVeggieDiaryController.java
> +    public BaseResponseDto<MyVeggieDiaryCount> selectDiaryCount(@PathVariable("myVeggieId") Long myVeggieId)  {
들여쓰기 맞춰주시면 좋을 것 같습니다

2024-07-31 05:17 UTC, MinchoGreenT requested changes
싱글 코멘트로 언급했지만, 대부분의 dto도 비슷한 것 같아 DTO 클래스명에 dto를 붙여 데이터통신 오브젝트라는 표시가 되도록 변경 요청드립니다!

2024-08-01 07:36 UTC, Ryeolee commented on src/main/java/com/modernfarmer/farmusspring/domain/myveggiegarden/controller/MyVeggieDiaryController.java
> +    public BaseResponseDto<MyVeggieDiaryCount> selectDiaryCount(@PathVariable("myVeggieId") Long myVeggieId)  {
들여쓰기 했습니다.

2024-08-01 07:36 UTC, Ryeolee commented on src/main/java/com/modernfarmer/farmusspring/domain/myveggiegarden/dto/DiaryAll.java
사실 거의 다 바꿔야해서 dto명은 리팩토링 시 모두 바꾸려고 했습니다!

2024-08-01 07:37 UTC, Ryeolee commented
전체적인 들여쓰기 및 dto는 리팩토링 시에 하려고 했습니다! 일단 AllDiary, DiaryAll 명이 제가 생각해도 어이가 없어섴ㅋ
DiaryAll -> SortedMyLikeDiary로 바꿨습니다!

2024-08-01 12:07 UTC, MinchoGreenT approved these changes

2024-08-01 12:08 UTC, MinchoGreenT commented
수고하셨습니다.

2024-08-01 12:08 UTC, merged